<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <link rel="stylesheet" type="text/css" href="/uikit-2.23.0/css/uikit.min.css"/>
        <link rel="stylesheet" type="text/css" href="/css/style.min.css"/>
        <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'/>

        <script src="/js/jquery-2.1.4.min.js"></script>
        <script src="/js/underscore-min.js"></script>
        <script src="/js/backbone-min.js"></script>
        <script src="/js/app.js"></script>

        <script src="/uikit-2.23.0/js/uikit.min.js"></script>

<!--
        <link rel="stylesheet" href="/uikit-2.23.0/css/components/notify.min.css">
        <script src="/uikit-2.23.0/js/components/notify.min.js"></script>
-->
    </head>
    <body  class="uk-height-1-1">
       
            <?php echo $this->content; ?>
           
    </body>
</html>
