
<div class="uk-vertical-align uk-text-center uk-height-1-1 app">

    <div class="uk-vertical-align-middle entry">
        <h1>ft</h1>
        <p>
        	<i>A no-nonsense URL shortening service.</i>
        </p>
        <form class="uk-panel uk-panel-box uk-form" action="/" method="post">
            <input type="text" class="url" id="url" placeholder="Enter URL to shorten"/>
        </form>

        <div class="uk-alert uk-alert-success" id="result">
        	 <a href="" class="uk-alert-close uk-close"></a>
        	 <p>

        	 </p> 
        </div>

    </div>
</div>  